### ISSUE TITLE
Hello DHUer

### ISSUE THREAD

**Issue by ghost** [DHU-On-Github/about#1]
学长你好!半夜debug发现了学长creat的这个repository就来报名了!

**Comment by polyrabbit** [comment]
Hi @XingLong9630 ，欢迎加入，很高兴看到我校这样愿意动手实践的学弟，我已经把你做的[QiuBo](https://github.com/XingLong9630/QiuBo)加入到我们的[awesome list](https://github.com/DHU-On-Github/awesome-DHU-works)里（想起当年我也上过Turbo的C语言课），期待你的更多作品！

BTW，早点睡~

**Comment by maiff** [comment]
66666
