### ISSUE TITLE
I am there

### ISSUE THREAD

**Issue by maiff** [DHU-On-Github/about#2]
学长第二个来报道~~

**Comment by polyrabbit** [comment]
欢迎欢迎，发邀请了，接收下。

**Comment by maiff** [comment]
我也有nice job可以看我写的东华教务处手机版，线上网址https://maiff.cn/ ，不过现在不更新了，github是https://github.com/maiff/DHU-jw

**Comment by polyrabbit** [comment]
哈哈，大家都拿教务网开刀，看来教务处的网站实在写的太烂了。你发一个PR到[awesome-DHU-works](https://github.com/DHU-On-Github/awesome-DHU-works)吧，我把你的`nice job`合并进去。
